version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: library
      # Optional: Define a custom user and password (instead of using root)
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234321
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # Optional: Mount a directory with .sql or .sh scripts to automatically run on startup
      - ./sql:/docker-entrypoint-initdb.d/
    restart: unless-stopped

volumes:
  mysql_data:
